# Import PyTorch library
import torch

# Define standard training function for one epoch
def train_epoch(model, dataloader, optimizer, criterion, device):
    # Set the model to training mode (enables dropout, batch norm updates, etc.)
    model.train()
    
    # Initialize accumulator for running training loss
    running_loss = 0.0
    # Initialize accumulator for running count of correct predictions
    correct_predictions = 0
    # Initialize accumulator for total number of processed samples
    total_samples = 0
    
    # Iterate over batches generated by the training DataLoader
    for batch_idx, (images, labels) in enumerate(dataloader):
        # Move images tensor to target device (CPU or CUDA GPU)
        images = images.to(device)
        # Move labels tensor to target device and reshape to [Batch, 1] for BCE loss
        labels = labels.to(device).unsqueeze(1)
        
        # Zero the parameter gradients to avoid accumulation from previous steps
        optimizer.zero_grad()
        
        # Forward pass: compute predictions by passing images through model
        outputs = model(images)
        
        # Calculate loss using the specified criteria (BCEWithLogitsLoss)
        loss = criterion(outputs, labels)
        
        # Backward pass: compute gradient of loss with respect to model parameters
        loss.backward()
        
        # Update weights based on current gradients using Adam optimization step
        optimizer.step()
        
        # Accumulate the loss multiplied by the batch size
        running_loss += loss.item() * images.size(0)
        
        # Apply sigmoid to raw logits to convert them to probabilities
        probabilities = torch.sigmoid(outputs)
        
        # Determine predicted binary classes (threshold at 0.5 probability)
        predictions = (probabilities >= 0.5).float()
        
        # Count the number of correct predictions in this batch
        correct_predictions += (predictions == labels).sum().item()
        
        # Add batch size to total samples count
        total_samples += images.size(0)
        
    # Calculate average loss across all samples in the dataset
    epoch_loss = running_loss / total_samples
    # Calculate average accuracy across all samples in the dataset
    epoch_accuracy = correct_predictions / total_samples
    
    # Return average training loss and accuracy for this epoch
    return epoch_loss, epoch_accuracy


# Define standard testing function
def test_epoch(model, dataloader, criterion, device):
    # Set the model to evaluation mode (disables dropout, batch norm updates, etc.)
    model.eval()
    
    # Initialize accumulator for running evaluation loss
    running_loss = 0.0
    # Initialize accumulator for running count of correct predictions
    correct_predictions = 0
    # Initialize accumulator for total number of processed samples
    total_samples = 0
    
    # Disable gradient computation for efficiency and safety during evaluation
    with torch.no_grad():
        # Iterate over batches generated by the test DataLoader
        for images, labels in dataloader:
            # Move images tensor to target device
            images = images.to(device)
            # Move labels tensor to target device and reshape to [Batch, 1]
            labels = labels.to(device).unsqueeze(1)
            
            # Forward pass: compute predictions
            outputs = model(images)
            
            # Calculate loss using the specified criteria
            loss = criterion(outputs, labels)
            
            # Accumulate the loss multiplied by the batch size
            running_loss += loss.item() * images.size(0)
            
            # Apply sigmoid to raw logits to convert them to probabilities
            probabilities = torch.sigmoid(outputs)
            
            # Determine predicted binary classes (threshold at 0.5 probability)
            predictions = (probabilities >= 0.5).float()
            
            # Count the number of correct predictions in this batch
            correct_predictions += (predictions == labels).sum().item()
            
            # Add batch size to total samples count
            total_samples += images.size(0)
            
    # Calculate average test loss across all samples
    epoch_loss = running_loss / total_samples
    # Calculate average test accuracy across all samples
    epoch_accuracy = correct_predictions / total_samples
    
    # Return average test loss and accuracy for this epoch
    return epoch_loss, epoch_accuracy
